// <auto-generated />
namespace testweb2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0-preview7-19363-02")]
    public sealed partial class co1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(co1));
        
        string IMigrationMetadata.Id
        {
            get { return "202011031710135_co1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
